sudo : required
language: generic 
services:
    - docker

before_install:
    - docker build -t appa253/react-test -f ./client/Dockerfile.dev ./client



after_success:
    - docker build -t appa253/multi-client ./client
    - docker build -t appa253/multi-nginx ./nginx
    - docker build -t appa253/multi-server ./server
    - docker build -t appa253/multi-worker ./worker
# LOGIN to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push image to docker hub
    - docker push appa253/multi-client
    - docker push appa253/multi-nginx
    - docker push appa253/multi-server
    - docker push appa253/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket: "elasticbeanstalk-us-west-2-539062601900"
    bucket_path: "multi-docker"
    on:
        branch: master
    edge: true
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    env:
        global:
        - secure: WkvtffTfTd0dOyXoz+4v8f96cj301wR7X17A34hUQ8+FnlktGJTqF2TUOYMimkUntHp6V77xdAM9UHRscRzOIgtkt5zJf3/+ayC9nl4NWzD+5gynnpWUrzo0UtLkXALPJmwgSMK4tmpY/RQaGRHJXw6ZSnPAz9i1tuwZmofIbs528KggjmiQ5vicWtj/JV8S27AuRScWJpkAwnj34wPp8il7JCGnHC8TmJPLpD3p0+82WuPFGTpnDZQTqVxCATNOK7oTQMvwL5DiP2o6dVi1azzIzpzrQKNDt6myGneFHLSGsXQ9sNn0rRdwtIJSZVTZk3b5Pu7jMYJwLAlTig+e3+yro2vNhqW7D2UuxgwAgmXX4QmnW3FhZL3hpe4bi4QVVgk23flyKzZsXYrTmq6Bmii5slKgj0i3l15P9PoMs65uxgjmRQZQJEHhJV7KZ2HpzkiEPJDInvgxvEgrKT3LVDuRXenNK6srT81O3YFd4Dy83ughIyYr9UKiHw90KOd/86Daw+W/6R2fHnFbUSc7+Cti5gGeHeWq+CqsNiNbSgjH2I8OYYFu+QHrRrXqVSlL2a0KCS84Ucy4ytyu+IczgdIzoLKHZVf3dAu4mu90kVpxvRgUZuplkoOX856iKdX+LyNU0UzYxrvnDxienz7u6s7s3YP7K8CvptWD1BFe2mI=
        - secure: brHc43dy/R48h5sg7dj8CBw2B1trdO4jzTtbgiAeDC47AbiKWXSzq2+0JC1dNk44ORyF65uB2HXS3NnduwT1kQT3WwWH29/IPbY55+eJWFA15wrHGVJFGp3p+v2KTnLAe5YyA8HILQvYf5pn5ay69ps5R4JXddn7IFGbBb99SwH9kU3CGaOSyWIBPhXecKlG2zLdGW9lknlenHwfkTTqCeMfCogNica30yv0chlxSjaXmSPYtfJ/ZP1vyq9O9beC2mF/OdywxgyfXVMECxVzSNNmq2H7ip2ULBFQ9O21r0Gwk1N4FN+X2oVpKkSyI8uTr9trNopAYumKS9j5OyqpVLnPrIHeH2wUDCzSWPbv5Ydig8ppxFJ8sToseSVsvnpx24QnJO4XIZA+xqrZDmTK7S/IdE2SZ5GxuFy1En+7DTj33ZhW/x2fBmpKyvAelLo0AyQsXaBtPOcy8iCYG76Z3Bm1bWOolH3PnE1AaaFkK4qsfldvTyxZv8Jdhtw5XmM2p5IS+M0hdtN19qARDCkZbn6elOwZYE0rw6WkOBE4hPBUp/1dVKcPo3znf+ih5B3XBtwmL2HNZK3vxyRor7ETgigsT6wKoHed3Ok2u27yKlgrvyp17xniWh8cQdcPH28GS3dIXtA2q62gtVmK4IIgay0YmiWNct6Q48gB9/bqF2w=