sudo : required
language: generic 
services:
    - docker

before_install:
    - docker build -t appa253/react-test -f ./client/Dockerfile.dev ./client



after_success:
    - docker build -t appa253/multi-client ./client
    - docker build -t appa253/multi-nginx ./nginx
    - docker build -t appa253/multi-server ./server
    - docker build -t appa253/multi-worker ./worker
# LOGIN to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push image to docker hub
    - docker push appa253/multi-client
    - docker push appa253/multi-nginx
    - docker push appa253/multi-server
    - docker push appa253/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket: "elasticbeanstalk-us-west-2-539062601900"
    bucket_path: "multi-docker"
    on:
        branch: master
    edge: true
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
