sudo : required
language: generic 
services:
    - docker

before_install:
    - docker build -t appa253/react-test -f ./client/Dockerfile.dev ./client



after_success:
    - docker build -t appa253/multi-client ./client
    - docker build -t appa253/multi-nginx ./nginx
    - docker build -t appa253/multi-server ./server
    - docker build -t appa253/multi-worker ./worker
# LOGIN to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push image to docker hub
    - docker push appa253/multi-client
    - docker push appa253/multi-nginx
    - docker push appa253/multi-server
    - docker push appa253/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket: "elasticbeanstalk-ap-south-1-539062601900"
    bucket_path: "multi-docker"
    on:
        branch: master
    edge: true
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    env:
        global:
        - secure: Odf5epZCiiwtPZqd0+KxEHkFtxPTZb6cI3BBESTUqbSeWDRSiNpWizjxtdtwBJvTHFPd9OCxZuQUiBv5JM1pJFqOJuyrkaDPCGlD5mKQGLh33wNvbENoVYvubfkhlNFVnFczx0IsD/x//fDV9CunnaD2wB4/0meODHXsEgJOc2OH59+75n50IhYC3ptxArK+osDfZYkONYbsU3mWgSDGiRy9hjW7L8PpGT1utlwvpTsM4fYqX3nJnGpxlrdmXrNMORHb+80ydnPhn8ZetT0BqjcW2paRanfqdA9wb0NfY9A2g0t1eJ3NGSuLGenVQAJ5kjgxDm7sKSr1L9gRBupj+lhWyq+PTZpmSTWG2BHScTzyKAbIEZPuG8IKSWEZvHfsEfN4CXf8Y541dbLgp+l28OW51BvzXTlrPS/Tk/QeMB7br2jLpNItcq8yYdBkeqjfcIl8OV4KFUTPp3w81v3Du9yJX3HEvkZXqdPOWQOJgeyubhbsekNYXX+bC4SdY0yVUaUAEF/Cuzk0ctS53bo1ye+x57aajU7YeiJ0NcqBDSrivXEjY4lOqKRXNbonOwFQHHzdgpMYHmNEQhsZHCGYAbelsqbaUM2AIGy2p/XwgwSgxx99wgvTfgz4u325NzAJJh7+nCLlEtv/AKL0+3jdoUCQJWvq198hag8e+W8o/5Q=
        - secure: awT7J9GHt68vuqcE3LDJ89xErI37evvqNBo2crZm0LN9YHAvAPTigfGgvnnxGl8vK/yS4tZlYdNR5RKRHsDmTewldim2+ZDWZ8RgZxRVOtqLDc7AWMhp6pvduxNmNu79XYmwK7NPjH9dFt3BrR4XEHCCA807Se86GDmJn6KiRG8VONCDkpncv/1Q+yfFINFl2ZQSxA4/OY02l6kPr7YYHPjwHXcmG+1bsPGLiXlJzKCX6BF8juQQFn+6kBUvmAZ6IJLogyh4aNB1AmZgoJhO6pbakHt0u3V2hkZOZJaqcnPPLsFu8hch+CzDPsvdGw8cuTN41QR/CpRiBnp1hbvLE877ZWUodmuif+xnAfVxW2VI/EBzuyNGyiGF5I2MEpAyUJXf/xMZJ582Q5DtANn0ARd6JBZQCbvwH1lMoUF9vlIpirQT4hEXszzvB5GjPtF8I7QlvEYjoQhvZC355mXXeesKROag+qQgOFTxjfIuBkNgf479pQEFgDnTzSY+6B52e8RUzZcREfm/sL6Fw8/a1LNbekhUSlEwQpsPcf6CEngR3AP7vIT6aJDbhHxrKQvCSN8gP2F8vihscSYnBYDcio5YbfY/NSIF9fF2dwutfsVIsXsmywzgTAm6yPy64acRcnQcde7uYLOvJaO0DqCRqMvCkkc5fQukv0JoQn3u7S0=